### ISSUE TITLE
MiddleWare problem

### ISSUE THREAD

**Issue by kill4food** [fbsamples/graph-api-webhooks-samples#12]
When i deploy the cloud code on parse server i get the following error on log:
 Error: Most middleware (like bodyParser) is no longer bundled with Express and must be installed separately. Please see https://github.com/senchalabs/connect#middleware.
    at Function.Object.defineProperty.get (/usr/src/app/node_modules/express/lib/express.js:99:13)
    at Object.<anonymous> (/usr/src/app/data/cloud/main.js:12:16)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/src/app/cloudCodeWrapper.js:4:20)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at new ParseServer (/usr/src/app/node_modules/parse-server/lib/ParseServer.js:365:9)

**Comment by adamgross42** [comment]
Hey @kill4food, this example was designed for the hosted Parse platform, I don't believe it has been tested with the open source platform.  Feel free to put up a pull request for an example based on the open source Parse platform!
