### ISSUE TITLE
Problems with POST requests on Heroku

### ISSUE THREAD

**Issue by kill4food** [fbsamples/graph-api-webhooks-samples#13]
Hi,
I created a subscription to my Heroku instance and i manage to receive POST requests, but when i check up the logs in the server i see there is a failure on the server:
`2017-03-10T17:01:34.134333+00:00 app[web.1]: Facebook request body:
2017-03-10T17:01:34.134352+00:00 app[web.1]: request header X-Hub-Signature found, validating
2017-03-10T17:01:34.135641+00:00 app[web.1]: Error: No Secret Found
2017-03-10T17:01:34.135643+00:00 app[web.1]:     at Signature.isValid (/app/node_modules/express-x-hub/lib/signature.js:20:30)
2017-03-10T17:01:34.135644+00:00 app[web.1]:     at IncomingMessage.req.isXHubValid (/app/node_modules/express-x-hub/lib/signature.js:15:16)
2017-03-10T17:01:34.135645+00:00 app[web.1]:     at /app/heroku/index.js:41:13
2017-03-10T17:01:34.135645+00:00 app[web.1]:     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
2017-03-10T17:01:34.135646+00:00 app[web.1]:     at next (/app/node_modules/express/lib/router/route.js:131:13)
2017-03-10T17:01:34.135647+00:00 app[web.1]:     at Route.dispatch (/app/node_modules/express/lib/router/route.js:112:3)
2017-03-10T17:01:34.135648+00:00 app[web.1]:     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
2017-03-10T17:01:34.135648+00:00 app[web.1]:     at /app/node_modules/express/lib/router/index.js:277:22
2017-03-10T17:01:34.135649+00:00 app[web.1]:     at Function.process_params (/app/node_modules/express/lib/router/index.js:330:12)
2017-03-10T17:01:34.135650+00:00 app[web.1]:     at next (/app/node_modules/express/lib/router/index.js:271:10)
2017-03-10T17:01:34.126719+00:00 heroku[router]: at=info method=POST path="/facebook" host=xxx.herokuapp.com request_id=xxxxxxxxxxxxxxxxxxxxxxxxxxx fwd="31.13.98.112" dyno=web.1 connect=0ms service=2ms status=500 bytes=232 protocol=https`

**Comment by kill4food** [comment]
UPDATE:
The problem was fixed after i set the config var APP_SECRET on Heroku.
But now there is a new problem:
After validation succeeds it sends a response in the line `res.send('Verified!\n');`
And then it tries to send another response in the line `res.sendStatus(200);`

In order to fix that i had to comment the `res.send('Verified!\n');` line

**Comment by adamgross42** [comment]
Looks like this was resolved.

**Comment by dharaneesh127** [comment]
Use get in the place of post. It'll work fine. Thank me later.
